steps:
  - id: artifactregistry-login
    name: gcr.io/cloud-builders/npm
    args: ['run', 'artifactregistry-login', '--', '--repo-config', '.npmrc', '--credential-config', '.npmrc']
  - id: publish
    name: gcr.io/cloud-builders/npm
    args: ['run', 'publish']